### PR TITLE
Adding info

### PR DESCRIPTION
**Pull request by shilpiprd**

### CODE REVIEW

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Please Make It Header Like this https://github.com/plxity/achievementsof.life#how-to-add-your-achievements-page


image





> You Can Review your Page here: https://achievementsof-life-git-fork-shilpiprd-shilpi-plxity.vercel.app/Shilpi_

**Comment by shilpiprd** [comment]
Are you asking me to reduce the size of headers ? 
Coz when i opened other profiles they looked pretty similar...

**Comment by plxity** [comment]
@shilpiprd Make the file structure in the way it is mentioned. 
You can check how others have written. 
I'm talking about the header changes. Rest all is fine.

**Comment by shilpiprd** [comment]
Is this OK?

**Pull request closed without merging**
