### PR TITLE
added whovivekshukla profile and linkedin button feature

### PR DESCRIPTION
**Pull request by whovivekshukla**
I have added my folder in users directory and have also added Linkedin Button Feature

### CODE REVIEW

**Comment by plxity** [comment]
There are changes in the file other than your markdown. Can you please remove those changes and then we can merge the PR?

**Comment by whovivekshukla** [comment]
I’ve added LinkedIn button, but you can just go ahead and delete the PR.

**Comment by plxity** [comment]
@whovivekshukla I'm talking about the changes in the other files apart from your markdown file.

**Comment by whovivekshukla** [comment]
closing the pull request

**Pull request closed without merging**
